import * as THREE from 'three';
import { OBJLoader } from 'three/addons/loaders/OBJLoader.js';

let humanGroup = null;
let currentPosition = [1.0, 1.75, 1.0]; // Room center (width=2.0, depth=3.5, height=1.0 for pelvis)
let isHumanEnabled = false;

function createPlaceholder(group) {
    const geometry = new THREE.CapsuleGeometry(0.3, 1.2, 4, 16);
    const material = new THREE.MeshPhysicalMaterial({
        color: 0x4ade80,
        transparent: true,
        opacity: 0.6,
        roughness: 0.2,
        metalness: 0.1,
        side: THREE.DoubleSide
    });
    const body = new THREE.Mesh(geometry, material);
    body.position.set(0, 0, 0.9);
    body.rotation.x = Math.PI / 2;
    
    // Add edges for better visibility
    const edges = new THREE.EdgesGeometry(geometry);
    const line = new THREE.LineSegments(
        edges, 
        new THREE.LineBasicMaterial({ color: 0xffffff, transparent: true, opacity: 0.3 })
    );
    body.add(line);
    group.add(body);
}

/**
 * Creates a 3D human model in the scene. Tries to load the real .obj generated by backend, falls back to placeholder.
 */
export function createHuman(scene, offset) {
    if (humanGroup) return;

    humanGroup = new THREE.Group();
    // Apply offset so Sionna coordinate (1.0, 1.75) matches Three.js render center
    // Fallback to 0 if offset.z is undefined (which happens because main.js passes {x,y})
    humanGroup.position.set(
        currentPosition[0] + offset.x, 
        currentPosition[1] + offset.y, 
        currentPosition[2] + (offset.z || 0.11)
    );
    humanGroup.visible = false;
    scene.add(humanGroup);

    const loader = new OBJLoader();
    const objPath = `/human.obj?t=${Date.now()}`;
    
    loader.load(
        objPath,
        (object) => {
            const material = new THREE.MeshPhysicalMaterial({
                color: 0x60a5fa, // Light blue to differentiate from the green placeholder
                transparent: true,
                opacity: 0.6,
                roughness: 0.3,
                metalness: 0.1,
                side: THREE.DoubleSide
            });

            object.traverse((child) => {
                if (child.isMesh) {
                    child.material = material;
                    const edges = new THREE.EdgesGeometry(child.geometry);
                    const line = new THREE.LineSegments(edges, new THREE.LineBasicMaterial({ color: 0xffffff, transparent: true, opacity: 0.15 }));
                    child.add(line);
                }
            });

            // SMPL native coordinates are usually Y-up. Rotate PI/2 to make it Z-up to match Sionna.
            object.rotation.x = Math.PI / 2;
            object.rotation.y = Math.PI; // Face the other direction horizontally
            
            humanGroup.add(object);
            console.log("✅ SMPL human.obj rendered in Frontend!");
        },
        (xhr) => {},
        (error) => {
            console.warn("⚠️ Could not load /human.obj. Using capsule placeholder instead.");
            createPlaceholder(humanGroup);
        }
    );
}

export function setHumanVisible(visible) {
    isHumanEnabled = visible;
    if (humanGroup) {
        humanGroup.visible = visible;
    }
}

export function getSmplParams() {
    if (!isHumanEnabled) return null;
    
    // Return parameters for backend SMPL generation
    // Transl takes X, Y, Z. But Sionna uses standard coords.
    return {
        transl: currentPosition,
        global_orient: [0.0, 0.0, 0.0],
        betas: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        body_pose: new Array(69).fill(0.0) // Neutral pose
    };
}
