import * as THREE from 'three';
import { OBJLoader } from 'three/addons/loaders/OBJLoader.js';

let humanGroup = null;
let currentPosition = [1.0, 1.75, 1.0]; // Room center (width=2.0, depth=3.5, height=1.0 for pelvis)
let isHumanEnabled = false;
let roomOffset = { x: 0, y: 0, z: 0.11 };

// Animation state
let isAnimating = false;
let currentFrame = -1;
let totalFrames = 0;

const humanMaterial = new THREE.MeshPhysicalMaterial({
    color: 0x60a5fa, // Light blue
    transparent: true,
    opacity: 0.6,
    roughness: 0.3,
    metalness: 0.1,
    side: THREE.DoubleSide
});

function createPlaceholder(group) {
    const geometry = new THREE.CapsuleGeometry(0.3, 1.2, 4, 16);
    const material = new THREE.MeshPhysicalMaterial({
        color: 0x4ade80,
        transparent: true,
        opacity: 0.6,
        roughness: 0.2,
        metalness: 0.1,
        side: THREE.DoubleSide
    });
    const body = new THREE.Mesh(geometry, material);
    body.position.set(0, 0, 0.9);
    body.rotation.x = Math.PI / 2;
    
    // Add edges for better visibility
    const edges = new THREE.EdgesGeometry(geometry);
    const line = new THREE.LineSegments(
        edges, 
        new THREE.LineBasicMaterial({ color: 0xffffff, transparent: true, opacity: 0.3 })
    );
    body.add(line);
    group.add(body);
}

function loadObjIntoGroup(group, objUrl) {
    const loader = new OBJLoader();
    
    loader.load(
        objUrl,
        (object) => {
            // Remove all existing children from group
            while (group.children.length > 0) {
                const child = group.children[0];
                group.remove(child);
                if (child.geometry) child.geometry.dispose();
            }

            object.traverse((child) => {
                if (child.isMesh) {
                    child.material = humanMaterial.clone();
                    const edges = new THREE.EdgesGeometry(child.geometry);
                    const line = new THREE.LineSegments(edges, new THREE.LineBasicMaterial({ color: 0xffffff, transparent: true, opacity: 0.15 }));
                    child.add(line);
                }
            });

            // SMPL native coordinates are usually Y-up. Rotate PI/2 to make it Z-up to match Sionna.
            object.rotation.x = Math.PI / 2;
            object.rotation.y = Math.PI; // Face the other direction horizontally
            
            group.add(object);
        },
        () => {},
        (error) => {
            console.warn(`⚠️ Could not load ${objUrl}. Using capsule placeholder.`);
            createPlaceholder(group);
        }
    );
}

/**
 * Creates a 3D human model in the scene. Tries to load the real .obj generated by backend, falls back to placeholder.
 */
export function createHuman(scene, offset) {
    if (humanGroup) return;

    roomOffset = { x: offset.x, y: offset.y, z: offset.z || 0.11 };

    humanGroup = new THREE.Group();
    humanGroup.position.set(
        currentPosition[0] + roomOffset.x, 
        currentPosition[1] + roomOffset.y, 
        currentPosition[2] + roomOffset.z
    );
    humanGroup.visible = false;
    scene.add(humanGroup);

    loadObjIntoGroup(humanGroup, `/human.obj?t=${Date.now()}`);
}

export function setHumanVisible(visible) {
    isHumanEnabled = visible;
    if (humanGroup) {
        humanGroup.visible = visible;
    }
    // If hiding, also stop animation
    if (!visible && isAnimating) {
        stopAnimation();
    }
}

/**
 * Update the human mesh by loading a new .obj from a URL. 
 * Used during animation to swap meshes per frame.
 */
export function updateHumanMesh(objUrl) {
    if (!humanGroup) return;
    loadObjIntoGroup(humanGroup, objUrl);
}

/**
 * Update the human's position in the 3D scene (with room offset applied).
 */
export function setHumanPosition(x, y, z) {
    currentPosition = [x, y, z];
    if (humanGroup) {
        humanGroup.position.set(
            x + roomOffset.x,
            y + roomOffset.y,
            z + roomOffset.z
        );
    }
}

/**
 * Start animation — update internal state
 */
export function startAnimation(numFrames) {
    isAnimating = true;
    currentFrame = 0;
    totalFrames = numFrames;
}

/**
 * Stop animation — reset internal state
 */
export function stopAnimation() {
    isAnimating = false;
    currentFrame = -1;
    totalFrames = 0;
}

/**
 * Update animation frame tracking
 */
export function setAnimationFrame(frameIndex, total) {
    currentFrame = frameIndex;
    totalFrames = total;
}

/**
 * Get the current animation state
 */
export function getAnimationState() {
    return {
        isAnimating,
        currentFrame,
        totalFrames,
    };
}

export function getSmplParams() {
    if (!isHumanEnabled) return null;
    
    // Convert scene coords (Z-up: x, y_depth, z_height) 
    // to SMPL coords (Y-up: x, y_height, z_depth)
    const smplTransl = [currentPosition[0], currentPosition[2], currentPosition[1]];
    
    return {
        transl: smplTransl,
        global_orient: [0.0, 0.0, 0.0],
        betas: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        body_pose: new Array(69).fill(0.0) // Neutral pose
    };
}
